# Basic Site Settings
locale: "en-US"
site_theme: "default"
title: "Maysaa Rais Portfolio"
title_separator: "-"
name: &name "Maysaa Rais"
description: &description "Quantitative Analyst | Data Science | Risk Models"
url: "https://MaysaaRais.github.io"  # Your GitHub Pages URL
baseurl: ""  # Leave empty for root domain
repository: "MaysaaRais/MaysaaRais.github.io"  # Your repository name

# Site Author Information
author:
  avatar: "profile.png"
  name: "Maysaa Rais"
  bio: "Quantitative Analyst with expertise in financial modeling, risk analysis, and Python."
  location: "Paris, France"
  email: "maysaarais@hotmail.com"
  linkedin: "https://www.linkedin.com/in/maysaa-r/"
  github: "https://github.com/MaysaaRais"

# Collection for Portfolio
collections:
  portfolio:
    output: true
    permalink: "/projects/:name/"

# Site Settings for SEO and Social Links
google_site_verification: "your-google-site-verification-code"  # Replace with your code

# Social Media Links
social:
  twitter: "your-twitter-handle"  # Replace with your Twitter username
  linkedin: "https://www.linkedin.com/in/maysaa-r/"
  github: "https://github.com/MaysaaRais"

# Publication Category (Optional for blog-like content)
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# SEO and Analytics (Optional)
analytics:
  provider: "google"
  google:
    tracking_id: "your-google-analytics-id"  # Replace with your Google Analytics ID

# Comments Configuration (Optional)
comments:
  provider: false  # Disable comments

# Markdown Processing and Conversion
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false

# Outputting
permalink: "/:categories/:title/"
timezone: Etc/UTC

# Plugins (Optional)
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
